### PR TITLE
Expose stomp.ConnectionListener on_disconnected() method

### PR DESCRIPTION
**Pull request by shahha**
#1

### CODE REVIEW

**Comment by snuids** [comment]
@shahha 

We are also using amqstomclient heavily inside containers that connect to ActiveMQ and having a steady connection is not that easy. So I like your change.

Can you just update the version number to 1.13 and I will accept the pull.

Cheers,

**Comment by shahha** [comment]
Updated version to 1.13 as suggested. :)

**Comment by shahha** [comment]
Thanks. I just realized that there is a version hardcoded in amqstompclient.py file as well.

**Comment by snuids** [comment]
Arg that's my fault :-(

**Comment by snuids** [comment]
Fixed

**Comment by shahha** [comment]
Perfect. Thanks. :)

**Comment by shahha** [comment]
Hey. Do you mind relasing new version 1.1.13 to pypi please?

**Pull request merged**
